# Application Name
spring.application.name=fleet-optimization

# Server Configuration & Optimization
server.port=${PORT:8080}
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

# PostgreSQL Database Configuration (Supports Render Env Vars / Local Neon Cloud)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-young-sea-abfnmy7t.eu-west-2.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_VecwGk8K2qgx}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
